version : '3'
services:
        python-anaconda:
                image : netsarang/python3-anaconda

                volumes:
                        - ./build/:/root/build/
                ports:
                        - "8888:8888" #Jupyter-notebook
                        - "5000:5000" #python-flask
                        - "40000:40000" #python-pytorch
                        - "6066:6066" #python-tensorflow

                container_name:
                        python-anaconda
                command:
                        /bin/bash -c "sh /root/build/pip-install.sh ; sleep infinity"
